version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    volumes:
      - .:/deploy/
    depends_on:
      - mongo
    networks:
      - web_nw

  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017-27019:27017-27019"
    networks:
      - web_nw

  redis:
    image: redis:4
    restart: always
    ports:
      - "6379:6379"
    networks:
      - web_nw
  
networks:
  web_nw:
    driver: bridge